### ISSUE TITLE
Average Recall and Average Precision are -1

### ISSUE THREAD

**Issue by Jinhui-Qin** [Tianxiaomo/pytorch-YOLOv4#233]
When I train my datasets, AP and AR are -1. And I check my annotations which are totally right. So I don't know how to deal with this problem, anyone can help me?

**Comment by RicoSuaveGuapo** [comment]
I trobuleshoot as follow 
1. Check the annotation (note that the **upper-left** is the original point of image axes)
2. Check the `Cfg.boxes` in `cfg.py`. It represents  num of bboxes in the train image. Adjust it if needed.
3. make sure the `get_image_id` in  `dataset.py` is properly coded.
4...
There are lots of things needed to be modified in this repo, I cannot recall all the modifications I made, however, be very careful about step 1. Since I spend around 3 days to find out that my own dataset annotation is based on lower-left...

**Comment by Jinhui-Qin** [comment]
> I trobuleshoot as follow 
> 
> 1. Check the annotation (note that the **upper-left** is the original point of image axes)
> 2. Check the `Cfg.boxes` in `cfg.py`. It represents  num of bboxes in the train image. Adjust it if needed.
> 3. make sure the `get_image_id` in  `dataset.py` is properly coded.
> 
> There are lots of things needed to be modified in this repo, I cannot recall all the modifications I made, however, be very careful about step 1. Since I spend around 3 days to find out that my own dataset annotation is based on lower-left...

Thank your reply very munch!!! I just change the Cfg.batch = 4 Cfg.subdivisions = 1, follwing Tianxiaomo's costom cfg, and it works.
